### ISSUE TITLE
ACE COMBAT™ 7: SKIES UNKNOWN (502500)

### ISSUE THREAD

**Issue by ToadKing** [ValveSoftware/Proton#2307]
# Whitelist Request
- Name of the game to be whitelisted: ACE COMBAT™ 7: SKIES UNKNOWN
- Steam AppID of the game: 502500

## System Information
- GPU: GTX 970
- Driver/LLVM version: NVIDIA 396.54.09
- Distro version: Ubuntu 18.10
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/ToadKing/0040c9221710247bcd15175cb809c3bb
- Proton version: 3.16-6 Beta

## I confirm:
- [x] that pressing the `Play` button in the Steam client is sufficient.
- [ ] that [runtime config options](https://github.com/ValveSoftware/Proton#runtime-config-options) are necessary to run the game.
- [x] that no workarounds other than PROTON_* env variables are necessary.

## Issues
- [ ] I haven't experienced any issues.
- [ ] There are no issues left open for this game.
- [x] Although I consider the gaming experience equal to Windows there are remaining issues:
- Game pops up a fatal error dialog box on exit.

**Comment by 200Puls** [comment]
Just edited this comment to say the game is working good for me. I reported a crash of the game earlier but it was my mistake as I copied launch options from another title and included PROTON_USE_WINED3D=1. Without that I can play the game fine. But I do have to use pule audio tweaks to get rid of stuttering.

**System Information**

- GPU: Vega 56
Driver/LLVM version: Mesa 18.3.3
Distro version: Ubuntu 18.10
Link to full system information report as Gist: https://gist.github.com/200Puls/c385425697ca54f10cba3e67dfbc6ac8
Proton version: 3.16-6 Beta

**Comment by 200Puls** [comment]
This is the exceptio the game throws:

LowLevelFatalError [File:F:\P4S3\bns_ws\patch1\Nimbus\Main\UE4\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp] [Line: 828] 
Rendering thread exception:
LowLevelFatalError [File:F:\P4S3\bns_ws\patch1\Nimbus\Main\UE4\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp] [Line: 1030] 
GameThread timed out waiting for RenderThread after 60.06 secs


0x000000007B44AF3D RaiseException() []
0x000000002F46BAF0 UnknownFunction []

**Comment by Zero86Sk** [comment]
if you have to use pulse audio tweaks than i'd uncheck " * that no workarounds other than PROTON_* env variables are necessary." cause that is a workaround

**Comment by ToadKing** [comment]
I did not have to set any environment variables on my machine. It appears there might be a bug with AMD and DXVK for the game.

**Comment by 200Puls** [comment]
Actually graphics is totally fine. 
The only problem I encountered is audio stuttering. This could be fixed by using PULSE_LATENCY_MSEC=30.

**Comment by Dvakote** [comment]
Game works fine most of the time, but I got around 4-5 crashes per 40 hours of gameplay.

It's always the same type of error:
LowLevelFatalError [File:F:\P4S3\bns_ws\patch1\Nimbus\Main\UE4\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Util.cpp] [Line: 294] 
Direct3DDevice->CreateTexture2D(TextureDesc,SubResourceData,OutTexture2D) failed 
 at F:\P4S3\bns_ws\patch1\Nimbus\Main\UE4\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Texture.cpp:441 
 with error E_FAIL, 
 Size=4096x4096x1 Format=DXGI_FORMAT_BC5_UNORM(0x00000053), NumMips=13, Flags=D3D11_BIND_SHADER_RESOURCE 
0x000000007B44AF3D RaiseException() []
0x0000000003D9C410 UnknownFunction []
Crash in runnable thread PoolThread 0 

Config:
    AMD Ryzen 5 1600 Six-Core Processor 3400 MHz
    Kernel: 4.19.20-1-MANJARO
    NVIDIA Corporation GeForce GTX 960/PCIe/SSE2
    Driver:  4.6.0 NVIDIA 415.27
    OpenGL: 4.6
    RAM:  16054 MB

**Comment by YellowApple** [comment]
Just a quick note to mention that aside from a 30-second-ish freeze at the main menu and a very minor visual glitch during replays (thin white outline around player's plane while flying through clouds), the game works absolutely flawlessly out-of-the-box for me on Proton 3.16-7 (just got through the full campaign).  My controller also worked flawlessly out-of-the-box (I'm sure Steam itself helps a lot here, but that's something I don't usually expect to consistently happen even for *Linux-native* games, let alone ones running on Wine/Proton; color me impressed!).  No configs, environment variables, or other workarounds/tweaks required; just click Play and it runs like a champ with excellent performance even on max settings.

Config:
CPU: AMD Ryzen Threadripper 1950X (16 cores, 32 threads)
Linux: 4.19.19 (Slackware64-current)
GPU: Radeon RX 570 (8192MB)
RAM: 32113 MB
Controller: Logitech Gamepad F310

**Comment by julienbenjamin** [comment]
No one here is getting a flickering black screen when launching the game sometimes?

**Comment by d10sfan** [comment]
I just replicated the Days Gone crash with another game, ACE COMBAT™ 7: SKIES UNKNOWN, where it works in 6.3-7 but not in Experimental.

I also tried removing the compatdata folder for that game but did not seem to help.

A log from that attempt: [steam-502500.log](https://github.com/ValveSoftware/Proton/files/7434397/steam-502500.log)

**Comment by ivyl** [comment]
@d10sfan, as kisak has pointed out in the other bug it's a different crash than Days Gone:

```
86982.574:0114:0118:err:module:open_builtin_file failed to load .so lib "/home/dnimon/.local/share/Steam/steamapps/common/Proton - Experimental/files/lib64/wine/x3daudio1_7.dll.so"
86982.575:0114:0118:err:module:import_dll Loading library X3DAudio1_7.dll (which is needed by L"Z:\\run\\media\\dnimon\\Storage\\SteamLibrary\\steamapps\\common\\ACE COMBAT 7\\Ace7Game.exe") failed (error c000007a).
86982.575:0114:0118:err:module:open_builtin_file failed to load .so lib "/home/dnimon/.local/share/Steam/steamapps/common/Proton - Experimental/files/lib64/wine/xapofx1_5.dll.so"
86982.576:0114:0118:err:module:import_dll Loading library XAPOFX1_5.dll (which is needed by L"Z:\\run\\media\\dnimon\\Storage\\SteamLibrary\\steamapps\\common\\ACE COMBAT 7\\Ace7Game.exe") failed (error c000007a).
```

Looks like it fails to load xaudio DLLs. I cannot reproduce that on my setup. This suggest that your Experimental installation may be corrupted. Just validating it may not be enough as Steam doesn't handle verifying many small files too well. Can you go to Steam Library and search for Proton there and then uninstall and reinstall Experimental? You may need to deselect it for every game that you used it for. Also please make sure that you don't have any beta branch enabled in the preferences. Also please make sure that your disk is not full.

**Comment by d10sfan** [comment]
@ivyl 

Thanks for the information, I attempted earlier deleting the entire Experimental folder and then clicking validate in Steam. 

I tried uninstalling and re-installing, then deleting the prefixes for the affected games, and that seemed to have fixed it. Thansk for the help and sorry for the confusion there.

**Comment by ToadKing** [comment]
Something I noticed with the game: If you try to use a Nintendo Switch Pro Controller with controller support enabled in Steam, the controller doesn't work and the game takes forever to load for some reason. I also got crashes when trying to load. Switching to another controller fixes both issues.

**Comment by brauliobo** [comment]
I'm having a lot of non-working game starts without the controller working. Nothing I try can make it work, like turning it off and on. It used to work better before proton 7.0. I'm having to restart steam as sometimes it works, although most of time it doesn't...

**Comment by 414n** [comment]
Since a little over a week ago, I noticed that the game stopped working altogether. Other games still work fine, for now I see the issue only with AC7.

I tried changing Proton version, recreating the wine prefix and also upgrading mesa to no avail.

My system info: [link](https://gist.github.com/414n/34891616266f2d4e4489173e8bbee632#file-steam-info-txt)
My runtime info: [link](https://gist.github.com/414n/28487314cd3d8ac511e98b878e6cb415#file-runtime_diag-txt)
[steam-502500.log.gz](https://github.com/ValveSoftware/Proton/files/12743303/steam-502500.log.gz)

One of the latest error messages in the log mentions a missing `steamservice.so` that cannot be found. I see only a 32-bit version of that library here: `~/.steam/bin32/steamservice.so`, but the game seems to try loading it from a 64-bit context (`gameoverlayrenderer64.dll`). Don't know if this is a meaningful error or not.

Could this issue be related to one of the latest Steam client beta updates? I currently have installed version `1695679261` (Steam Client Build Date:  Mon, Sep 25 10:23 PM UTC -08:00) of the client and the issue persists.

**Comment by kisak-valve** [comment]
Hello @414n, looking at the extended diagnostics information, something's broken the Vulkan render paths on your system in general, but somehow not with Steam Linux Runtime 3.0 (Sniper) (https://gist.github.com/414n/28487314cd3d8ac511e98b878e6cb415#file-runtime_diag-txt-L108, https://gist.github.com/414n/28487314cd3d8ac511e98b878e6cb415#file-runtime_diag-txt-L312)

Since that runtime environment is healthier than the rest for whatever reason, it might be interesting to test how the game behaves with Proton 8.0 (which uses that runtime environment) and follow up with your distro's package maintainer for mesa for your video driver issue.

**Comment by 414n** [comment]
Hello kisak, I can agree that those error messages are indeed strange, but I doubt that there's anything actually broken regarding Vulkan on my system as I have no issues playing other games using Vulkan directly or via DXVK/VKD3D-Proton regardless of the Proton version, like:
  - Sekiro (Proton-7.0-6)
  - Resident Evil 2 remake (Proton-7.0-6)
  - Path of Exile (Proton-Experimental)
  - Sea of Thieves (Proton-Experimental)
  - Killer instinct (Proton-8.0-3)

I just tried reverting to the stable Steam client and the game started working again, even with Proton-7.0-6. Reactivating the client beta broke it another time, so I think this is really related to one of the latest client beta updates.

Should I open a new issue in the ValveSoftware/steam-for-linux repo and link that here?

**Comment by smcv** [comment]
> Hello @414n, looking at the extended diagnostics information, something's broken the Vulkan render paths on your system in general, but somehow not with Steam Linux Runtime 3.0 (Sniper) (https://gist.github.com/414n/28487314cd3d8ac511e98b878e6cb415#file-runtime_diag-txt-L108, https://gist.github.com/414n/28487314cd3d8ac511e98b878e6cb415#file-runtime_diag-txt-L312)

I believe this is a false alarm. There's a regression in the diagnostic tool itself, which makes some of its checks crash with a use-after-free. Each runtime has its own copy of the diagnostic tool, so it's entirely possible to see the bug in some but not others. This is specific to the diagnostic tool itself, and does not affect games: all games should work normally with the affected runtimes (or not-work normally, if there's an unrelated reason for them to be broken).

I think @414n is using the Steam client beta, which contains a copy of scout that has the diagnostic tool bug; and the beta branch of soldier, which has the same bug; but they are using the general availability (stable, non-beta) version of sniper, which *doesn't* (currently) have the same bug. We know why this is happening, and it should be fixed in the next beta release of each runtime.

The diagnostic tool bug is unrelated to whether Ace Combat 7 works or not.

**Comment by smcv** [comment]
> There's a regression in the diagnostic tool itself

FYI:

For the scout runtime included with the Steam client, the diagnostic tool bug is present in the beta branch (scout 0.20230919.60656) and will be fixed in a future beta. I prepared a new 0.20231003.62137 build of scout today, but I can't predict how long that will take to make its way through the release pipeline.

For the soldier and sniper runtimes, the diagnostic tool bug is present in yesterday's updates to the general-availability branch, versioned 0.20230921.60881 and 0.20230919.60634 (it wasn't considered to be an important enough regression to justify delaying those updates). It has been fixed in yesterday's 0.20231002.x updates to the beta branches, which will be promoted to general-availability when they have had some more testing.

**Comment by 414n** [comment]
I Just tried switching again the Steam client from normal to beta (version `1697233589`) after reading about some client beta updates but the issue persists.

Is there something I can do to extract some more info to pinpoint the underlying issue?

EDIT 20231021: still does not work with beta client `1697755400` 
EDIT 20231215: finally started working again after installing beta client `1702667398`

**Comment by kisak-valve** [comment]
Ace Combat 7 opens no game window on Proton 8.0.4

Issue transferred from https://github.com/ValveSoftware/Proton/issues/7327.
@hirak99 posted on 2023-12-09T19:17:51:

# Compatibility Report
- Name of the game with compatibility issues: Ace Combat 7: Skies Unknown
- Steam AppID of the game: 502500

## System Information
- GPU: RTX 3090
- Video driver version: nvidia 545.29.06
- Kernel version: 6.6.4
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/hirak99/b31daeddf5355bd200532fb144a656d8
- Proton version: 8.0.4

## I confirm:
- [ x] that I haven't found an existing compatibility report for this game.
- [ x] that I have checked whether there are updates for my system available.

(Proton logs compress well if needed.)--> [steam-502500.log.gz](https://github.com/ValveSoftware/Proton/files/13625412/steam-502500.log.gz)


## Symptoms

The game shows no window, even though Steam UI's "PLAY" turns into "STOP" as if the game has launched and remains there.


## Reproduction

- Set Proton version to 8.0.4.
- Launch the game clicking "PLAY".
- "PLAY" turns into "LAUNCHING", and then to "STOP".
- No game window is visible; but Steam UI thinks the game has launched.
- Eventually you'll need to click "STOP" from Steam to kill whatever process may be running in the background as the game.

**Comment by mvrk69** [comment]
Hi,

I have been playing Ace Combat 7 (campaign) on Linux for long time without issues, but now i tried for the first time the multiplayer mode, and it's impossible to play, very slow/stuttering.

There is a report here (https://www.protondb.com/app/502500?device=pc) that mentions protontricks can help, but doesn't specify exactly how.

Does anyone knows how to fix the multiplayer being slow/stuttering?

My system:
OS: Fedora 40
Kernel: 6.9.12-200.fc40.x86_64
Display Server: X11
Graphics: NVIDIA GeForce GTX 1070
Graphics Driver: nvidia-driver-555.58.02-3.fc40.x86_64
Proton: 9.0-2

**Comment by hxdeci** [comment]
i received this game this morning as a gift and it crashes the entirety of Steam with a segfault upon launch. anyone know what's going on? tested both Proton 9 and Experimental

[system info gist](https://gist.github.com/hxdeci/9eed1c11cf2bdf683fe22484b8fe11c1)

[steam-502500.log](https://github.com/user-attachments/files/18247391/steam-502500.log)

**Comment by kisak-valve** [comment]
Hello @hxdeci, as an extra data point, please note what update channel you're using with the Steam client (the client itself) and if you're using the Steam client beta, if the game behaves differently when opting out off that.

**Comment by hxdeci** [comment]
> Hello @hxdeci, as an extra data point, please note what update channel you're using with the Steam client (the client itself) and if you're using the Steam client beta, if the game behaves differently when opting out off that.

okie doke, just tested on the stable release client, and it works fine! probably a regression in the beta client branch? sorry about that, will try to keep it in mind. thanks :]

**Comment by kisak-valve** [comment]
ACE COMBAT™ 7: SKIES UNKNOWN (502500) - Multiplayer stuttering

Issue transferred from https://github.com/ValveSoftware/Proton/issues/9503.
@IslingrB posted on 2026-02-15T19:13:48:

# Compatibility Report
- Name of the game with compatibility issues: ACE COMBAT™ 7: SKIES UNKNOWN
- Steam AppID of the game: 502500

## System Information
- GPU: NVIDIA RTX 4070 Ti SUPER
- Video driver version: 4.6.0 NVIDIA 590.48.01
- Kernel version: 6.17.0-14-generic
- Link to full system information report: [System information](https://gist.github.com/IslingrB/af72ad0fd6e487b09083a37b3c9f2ba8)
- Proton version: GE-Proton10-29 (but the issue has also been observed on Proton 9.0-4, Proton 10.0-4, Proton Hotfix & Proton Experimental)

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [ ] that I have checked whether there are updates for my system available.

## Symptoms

Multiplayer mode constantly stutters, both in-game and in menus. This issue begins as soon as the multiplayer menu is opened, and ends as soon as it is exited. Solo mode is unaffected and runs smoothly.


## Reproduction

Launch the game, enter the multiplayer menu. The stuttering starts from there, and persists in any submenu and multiplayer game.

## Additional notes
Precisions regarding the "I confirm" section:
- I have found an existing compatibility report for this game, though for a different issue. [A comment in that existing report also mentions the same problem I am encountering.](https://github.com/ValveSoftware/Proton/issues/2307#issuecomment-2269059760) The original report was however not about the stuttering issue, and I have been advised to create a separate report by Steam's support.
- BIOS, GPU driver, kernel & OS are all at their latest version. OS is Linux Mint 22.3 - Cinnamon 64-bit.
- [System Information](https://gist.github.com/IslingrB/af72ad0fd6e487b09083a37b3c9f2ba8)
- [Steam Runtime System Information](https://gist.github.com/IslingrB/087b75b34f91ece081208238387cc5b0)


## Attached files

The attached & linked (upload of the recordings has failed, the linked recordings are on a Google drive) files include a recording of the stutters in the multiplayer menu, another recording of the stutters in-game, and a Proton log corresponding to launching the game, opening the multiplayer menu, joining a game, playing for a bit then exiting the game.

[steam-502500.log](https://github.com/user-attachments/files/25327844/steam-502500.log)
[Menu stuttering](https://drive.google.com/file/d/1Fpi6J3WDxenQkpWSwh8jrZdeg1R8exIE/view?usp=drive_link)
[Game stuttering](https://drive.google.com/file/d/16Jbq2NpYfsBaSdI0MiItxQEpaoVUVeuB/view?usp=drive_link)
