### ISSUE TITLE
Project Cars (234630)

### ISSUE THREAD

**Issue by leillo1975** [ValveSoftware/Proton#244]
The game seems to work well, even with Force Feedback support in my Logitech G27 wheel , but it can't save profile and settings, showing a hint when this is needed.

With the lasts versions of Wine + DXVK  the Force Feedback functionality don't work , but I don't have problems saving profile and settings.

**Comment by FiXIDeA** [comment]
Cars doesn`t start on ubuntu 18.04. It crashes at start

**Comment by leillo1975** [comment]
In my case the game starts perfectly

**Comment by leillo1975** [comment]
As I reported in this issue https://github.com/ValveSoftware/Proton/issues/364#issuecomment-415685763 , Is impossible to calibrate the pedals of my G27 wheel, that is detected correctly by the game. If you go to game settings and start to calibrate it, this action finish without doing anything. Instead, is possible to calibrate the wheel normally.

**Comment by ronimc** [comment]
The same here. Works wonderfully, but not save.

**Comment by leillo1975** [comment]
Can you connect to the online servers for multiplayer?

**Comment by ronimc** [comment]
I did not try. Problems?

**Comment by leillo1975** [comment]
I can't connect (empty list), but the problem could be that there are no profile (saving problem)

**Comment by ronimc** [comment]
I tested and also empty list. I'm going to test multiplayer in lutris.

**Comment by ronimc** [comment]
In Lutris, wine+dxvk, online and save works.

**Comment by leillo1975** [comment]
but I suppose that no Force Feedback, isn't?

**Comment by vaincz** [comment]
Exactly same problem here. Works well, but can't save profile.

**Comment by Dygear** [comment]
I'm also having the issue that it seems to be unable to save the profile information anywhere. This is perhaps a simple permission issue with the directory it is trying to save too. Is there a way to pierce the veil and see what is going on behind the scene so that we can debug this information ourselves?

[Gist: Project Cars: `PROTON_LOG=1 %command%`](https://gist.github.com/Dygear/dacdb119bcdd24db84b36846cafa24d4)

**Comment by leillo1975** [comment]
Nobody can't found a solution to the saving problem with Proton? Is very strange that you can do it with wine+DXVK. This is a great game and it's a pity

**Comment by jmikkola** [comment]
It starts and runs reasonably well for me in 18.04 w/ Proton 3.7-8 and Nvidia driver 396, but it keeps showing errors about saving not working. It also hangs when I leave a race.

**Comment by leillo1975** [comment]
> I'm also having the issue that it seems to be unable to save the profile information anywhere. This is perhaps a simple permission issue with the directory it is trying to save too. Is there a way to pierce the veil and see what is going on behind the scene so that we can debug this information ourselves?
> 
> [Gist: Project Cars: `PROTON_LOG=1 %command%`](https://gist.github.com/Dygear/dacdb119bcdd24db84b36846cafa24d4)

Someone knows where this game save the profile?

**Comment by leillo1975** [comment]
Don't start with 3.16-4beta. Take a look on this. With 3.7.8 runs well

**Comment by rcgamer29** [comment]
> Don't start with 3.16-4beta. Take a look on this. With 3.7.8 runs well

Still works fine here except for the not saving that it.

**Comment by leillo1975** [comment]
> Don't start with 3.16-4beta. Take a look on this. With 3.7.8 runs well

Uninstalling game and installing it again, it works, and I can confirm that with this last update of Proton (3.16-4Beta) now works online. 

Please Valve, take a look on the profile saving issue. The game works perfect, even with Force feedback support. With wine the game don't have this problem with profile

**Comment by mercuriete** [comment]
Same problem.
Investigating a little bit..
the profile path is in:
```
.local/share/Steam/userdata/$steamid/234630/local/project cars/profiles 
```
if you change profiles permissions the problem persists
but is you do a

```
touch default.sav
```
Then project cars complaint about a corrupted file and the problem persist, so is something about that folder I think.
```
I tried doing chmod +777 profiles
```
and nothing happen.


Another good folder to insvestigate is:
```
steamapps/compatdata/234630/pfx/drive_c/users/steamuser/My Documents/Project CARS/dbgSession
```

there are a log file called app.log complaining something like:
```
[22:30:20:800][0x00000025] [ERROR] [UpgradeCatalogue::Load] Failed to load from data file 'upgrade\vehicleupgradecatalogue\lykan_hypersport.xml'.
```

I gave up about this problem I hope another person can investigate more.

**Comment by hswhite33** [comment]
I got about as far as @mercuriete a few weeks ago. I tried transferring my Windows save file to `.local/share/Steam/userdata/$steamid/234630/local/project cars/profiles` but got the same "corrupted file" issues.

It's worth noting that my `dbgSession/**/app.log` file from running the game in Windows has the same errors as listed by @mercuriete , so I don't think this is relevant.

**Comment by leillo1975** [comment]
IT FINALLY WORKS !!!!!!!

With the last version of Proton (3.16-5beta) the game now save our profile. Of course we can race Online and Force Feedback Works in my G27 Wheel.
I think that this game can be included in the **WHITELIST**

**Comment by Dygear** [comment]
Works great with Proton **3.16-5Beta**. Agree that it can be whitelisted once that goes out as stable.

**Comment by FictionX** [comment]
VR works as well with 3.16-5Beta, and settings (including centering, which kept us from actually getting into the cars) are saved.

**Comment by leillo1975** [comment]
> VR works as well with 3.16-5Beta, and settings (including centering, which kept us from actually getting into the cars) are saved.

If VR works, then.... WHITELIST!!!!

**Comment by kisak-valve** [comment]
Anyone seeing a substantial issue with this game that would block it from being white listed?

**Comment by leillo1975** [comment]
It would be nice if a couple more people confirmed that everything is OK.

**Comment by hswhite33** [comment]
Played it for an hour or so with no major issues. Confirmed that saving and loading works in Proton 3.16-5 beta. Logitech G29 working with force-feedback with no additional setup required. Performance seems good (~140fps on medium settings).

The only issue I've encountered is that the game goes to a black screen with a tiny icon-sized bit of colour in the top left corner when it loses focus. This has been the case for a lot of games that I've played (including Flatout 2, which is whitelisted), so I don't know if this is a blocker for whitelisting.

[System info](https://gist.github.com/hswhite33/35ee33c169a2676847266fc5bf4ceb03)

**Comment by leillo1975** [comment]
Yesterday night I was playing about two hours without any problem. The game runs pretty well with my GTX-1050Ti in Default graphics

**Comment by hswhite33** [comment]
After roughly 10 hours of play, I've encountered the first crash.

First instance: (sorry for the poor screenshot quality)
![imgur-2018_12_18-20 46 00](https://user-images.githubusercontent.com/14989982/50139610-054b8300-0307-11e9-8b12-29c18f045fbf.png)

And after closing and relaunching the game, and attempting to load the same race:
![imgur-2018_12_18-20 47 29](https://user-images.githubusercontent.com/14989982/50139613-054b8300-0307-11e9-8378-284ec2f9a932.png)

[Log file for the second run](https://github.com/ValveSoftware/Proton/files/2689441/steam-234630.log), I can't make much sense of this unfortunately, but a quick find of the address listed in the error dialog does come up with some `NtRaiseException` calls, which are presumably relevant (I had these calls showing up in the log file with Proton 3.16-4 when the save file failed to load, also)

**Comment by hswhite33** [comment]
The game doesn't seem to turn to a black screen when losing focus if I run it in a window instead of fullscreen. However, after returning focus to the game, my racing wheel stops working and I have to restart the game using mouse/keyboard and then the wheel works again.

I haven't had a chance to look into this issue properly or get log files, but I thought it might be worth mentioning here.

**Comment by kisak-valve** [comment]
`warn:module:load_dll Failed to load module L"nvcuda.dll"; status=c0000135` for gpu PhysX is just before the log goes awry.

@hswhite33, what race has the failing behavior? Is it easy to get to or is there a save you can share just before it?

**Comment by hswhite33** [comment]
@kisak-valve The race that I encountered the crashes on was race 3 of the Historic TC2 UK Trophy, at Silverstone International. It loaded successfully on the third attempt so I no longer have a save file that's up to this race (though given that it did succeed I doubt it's race-specific)

Also note that this log line `warn:module:load_dll Failed to load module L"nvcuda.dll"; status=c0000135` comes up during normal operation of the game too (with no crashes observed): 
[steam-234630.log](https://github.com/ValveSoftware/Proton/files/2693357/steam-234630.log)

I'll be playing this some more over the next few days; is there anything specific that I can do to help if this happens again?

**Comment by alasky17** [comment]
> The only issue I've encountered is that the game goes to a black screen with a tiny icon-sized bit of colour in the top left corner when it loses focus. This has been the case for a lot of games that I've played (including Flatout 2, which is whitelisted), so I don't know if this is a blocker for whitelisting.

@hswhite33 Which other titles are you seeing this with?  

> I'll be playing this some more over the next few days; is there anything specific that I can do to help if this happens again? 

Logs like that are probably the most useful thing, unless you can compare crashes and narrow down what might be the cause.

**Comment by hswhite33** [comment]
@alasky17 To name a few...

* Flatout 2 (this one may be a different issue as it goes to a completely black screen, and recovers if I switch workspaces)
* GRID
* Mirror's Edge
* Need for Speed: Hot Pursuit
* Need for Speed: SHIFT

**Comment by leillo1975** [comment]
With the last version of Proton 4.11-7, FFB in this game is lost, like another games like Project Cars 2, RACE 07 or F1 2019.
If you change to 4.2-9, everything goes normal again. I think that the last version of proton has a regression with FFB support

**Comment by leillo1975** [comment]
> With the last version of Proton 4.11-7, FFB in this game is lost, like another games like Project Cars 2, RACE 07 or F1 2019.
> If you change to 4.2-9, everything goes normal again. I think that the last version of proton has a regression with FFB support

New version of Proton (4.11-8) stills breaking Force Feedback in this and a lot of racing games. Other games like:
[-Project Cars 2](https://github.com/ValveSoftware/Proton/issues/908)
[-RACE 07](https://github.com/ValveSoftware/Proton/issues/1212)
[-GT Legends](https://github.com/ValveSoftware/Proton/issues/2728)


https://github.com/ValveSoftware/Proton/issues/3194

**Comment by leillo1975** [comment]
With the last version of proton (4.11-10), the game has a good Force Feedback. Good Work!

**Comment by kisak-valve** [comment]
Not properly detecting input from pedals anymore. PROJECT CARS

Issue transferred from https://github.com/ValveSoftware/Proton/issues/3507.
@Lepidos posted on 2020-02-09T15:58:51:

# Compatibility Report
- GAME: PROJECT CARS
- steamappid: 234630

## System Information
 - Proton version: 5.0-1

## Symptoms 
Using Logitech G29, game detects multiple inputs pressing pedals. Cannot properly assign throttle or brake. 
Wheel and pedals inputs are correctly detected with previous Proton versions.

**Comment by kisak-valve** [comment]
Hello @Lepidos, please add [`PROTON_LOG=1 %command%`](https://github.com/ValveSoftware/Proton#runtime-config-options) to the game's launch options, reproduce the regression and drag and drop the generated $HOME/steam-$APPID.log into the comment box. Also, please confirm that Proton 4.11-12 is the version of Proton which is unaffected by this regression.

**Comment by Lepidos** [comment]
Changed from older version 4.11-12 back to Proton 5.0-1 to create the log file and the pedals are working properly. 
It's all good

**Comment by ingmarcosp** [comment]
I have problem with the detection of the Logitech G29:
Proton 5.0.3

Log file:
[steam-234630.log](https://github.com/ValveSoftware/Proton/files/4272332/steam-234630.log)

[Edit]
No problem with Proton 4.2.9

**Comment by alasky17** [comment]
@ingmarcosp Could you be a bit more specific about the failure vs. success behavior just in case I am misunderstanding you?  Also, could you take a log of the success case when you get a chance? 

Did you mean 4.2-9 or 4.11-12?

**Comment by leillo1975** [comment]
I can say that yesterday I could play the game normally with my G29 using 5.0-3

**Comment by ingmarcosp** [comment]
> @ingmarcosp Could you be a bit more specific about the failure vs. success behavior just in case I am misunderstanding you? Also, could you take a log of the success case when you get a chance?
> 
Does not recognize the wheel at all, no axis, no buttons.

Sorry about that, already I edit the post, the last version that work is 4.2.9
> Did you mean 4.2-9 or 4.11-12?

Here you have the log of success case (proton 4.2.9)
[steam-234630.log](https://github.com/ValveSoftware/Proton/files/4284127/steam-234630.log)

I'm using
OpenSuse 15.1 
kernel 4.12.14-lp151.28.36-default
Steam Beta 1583199626

I try, and doesn't work
G29 in mode G27 with pyLiinuxWheel
delete the pfx 
reinstall the game

**Comment by alasky17** [comment]
@ingmarcosp Thank you for the details and for the log!  One more thing that could potentially give a hint at what is going on -- could you add the following logging channels and get a log of the failure on proton 5.0-3?  
`+hid,+hidp,+hid_report,+plugplay,+rawinput,+dinput,+xinput,+joystick,+setupapi`

Getting the same log of the wheel working on 4.2-9 might be interesting as well.

**Comment by ingmarcosp** [comment]
ok, success log:

[steam-234630.success.log](https://github.com/ValveSoftware/Proton/files/4289177/steam-234630.success.log)

fail log:
[steam-234630.fail.log](https://github.com/ValveSoftware/Proton/files/4289180/steam-234630.fail.log)

I notice that if I run the 
`../proton5dir/ ~> ./wine control`
Dosen't have the "game controls" (I don't know what is the translation) and get:
```
0009:err:module:load_so_dll failed to load .so lib "/home/koxmoz/.local/share/Steam/steamapps/common/Proton 5.0/dist/bin/../lib/wine/dinput8.dll.so": libSDL2-2.0.so.0: clase ELF errónea: ELFCLASS64
0009:err:module:import_dll Loading library dinput8.dll (which is needed by L"C:\\windows\\system32\\joy.cpl") failed (error c000007a).
```

unlike:
`../proton5dir/ ~> ./wine64 control`
have it and doesn't fiail

**Comment by schabrackes** [comment]
Hello, 
I'm trying since weeks to get the FFB to work on my G27. 
Kernel module: new-lg4ff (https://github.com/berarma/new-lg4ff)
Proton tested: 4.2-9 and 5.0-4

I tried it with the "ffbwrap --update-fix --direction-fix --ignore-set-gain --offset-fix ..." and without, no change. Buttons, pedals and the wheel are all working just no force feedback...

**Comment by ingmarcosp** [comment]
> ok, success log:
> 
> [steam-234630.success.log](https://github.com/ValveSoftware/Proton/files/4289177/steam-234630.success.log)
> 
> fail log:
> [steam-234630.fail.log](https://github.com/ValveSoftware/Proton/files/4289180/steam-234630.fail.log)
> 
> I notice that if I run the
> `../proton5dir/ ~> ./wine control`
> Dosen't have the "game controls" (I don't know what is the translation) and get:
> 
> ```
> 0009:err:module:load_so_dll failed to load .so lib "/home/koxmoz/.local/share/Steam/steamapps/common/Proton 5.0/dist/bin/../lib/wine/dinput8.dll.so": libSDL2-2.0.so.0: clase ELF errónea: ELFCLASS64
> 0009:err:module:import_dll Loading library dinput8.dll (which is needed by L"C:\\windows\\system32\\joy.cpl") failed (error c000007a).
> ```
> 
> unlike:
> `../proton5dir/ ~> ./wine64 control`
> have it and doesn't fiail

With the lastest version Proton 5.0-5 wheels detection and FF are back!

**Comment by FabianoLothor** [comment]
![image](https://user-images.githubusercontent.com/2192995/81125692-4863c180-8f0f-11ea-9736-720bf97f85f6.png)

**Comment by cain05** [comment]
Picked up a G920 last night and gave this a try.  I'm experiencing two issues.  I tried both the default version of proton steam selects for the game, and proton 6.3-1.  I'm running Kubuntu 20.04.2.

1) The brake and clutch pedals don't work by default.  Once I assign them in the game settings, they work, so it's not a big deal.
2) Alt-Tabbing out of the game causes all input except the mouse to stop working.  The only way to quit the game is to Alt+F4, or Alt+Tab out and kill the process.

**Comment by schabrackes** [comment]
> Hello,
> I'm trying since weeks to get the FFB to work on my G27.
> Kernel module: new-lg4ff (https://github.com/berarma/new-lg4ff)
> Proton tested: 4.2-9 and 5.0-4
> 
> I tried it with the "ffbwrap --update-fix --direction-fix --ignore-set-gain --offset-fix ..." and without, no change. Buttons, pedals and the wheel are all working just no force feedback...

Hi, 
some feedback to my first post after >1 year playing now:
I got the FFB working by adding the "haptic" use flag to libsdl2 - that's a Gentoo specific thing I guess. 
So Project Cars is working now for me since 300+ hours with a G27 using new-lg4ff :-) 

I have had issues with Proton 5.13 and 6.3. Only Proton 5.0 was working almost stable. I had game crashes driving LeMans (in the first round) and Nordschleife (after 30 minutes driving). Furthermore some graphic glitches in the sky and engine sound hangs. 

This all went away once I set PROTON_NO_ESYNC=1. Now I'm on Proton 5.13 and everything is pretty solid and 100% functional. Nevertheless with Proton 6.3 the force feedback is gone. So I'm on 5.13 now. 

Hope this helps someone. Cheers!

**Comment by kisak-valve** [comment]
Project Cars showing error when assigning buttons with gaming wheel

Issue transferred from https://github.com/ValveSoftware/Proton/issues/5233.
@MoriGM posted on 2021-10-20T14:00:28:

# Compatibility Report
- Name of the game with compatibility issues: Project Cars
- Steam AppID of the game: 234630

## System Information
- GPU: RX 580 8G
- Driver/LLVM version: Mesa 22.0.0-devel
- Kernel version: 5.13.13
- Link to full system information report as [Gist](https://gist.github.com/): https://gist.github.com/MoriGM/fb8c6de3e8f7207ef027d1e537cbbdaa
- Proton version: 6,3-7

## I confirm:
- [X] that I haven't found an existing compatibility report for this game.
- [X] that I have checked whether there are updates for my system available.


[steam-234630.log](https://github.com/ValveSoftware/Proton/files/7381750/steam-234630.log)

## Symptoms
Logitech Driving Force GT and Thrustmaster T150RS both getting detected but when reassigning the buttons it will throw an error saying to many inputs.

## Reproduction
1. Starting Project Cars.
2. Going into the Options.
3. Going into Input Settings.
4. Assigning a button.

I think this problem happens because wine passes the wheel through as a event and as a joystick.
But i couldn't find any way to only use one of the two.
